name: example
description: Sample uses of the dynamic carousel

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_navigator: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/delay.png
    - assets/spanner.png
    - assets/totals.png
    - assets/train.png
    - assets/wheelchair.png